### ISSUE TITLE
Choose automatically the best video quality (and audio quality)

### ISSUE THREAD

**Issue by Gol-D-Ace** [Hyphen-ated/DJBot#20]
Currently the youtube player does choose auto (which is 360p in most cases).

Could you please make it so it uses the highest quality? (improving the audio quality)

**Comment by Hyphen-ated** [comment]
Hmm, apparently you can't make a youtube embed play at high quality unless the embed is sized big enough for the full resolution of the hd video, and I don't really want to make it that big. Do you know a good way around this?

**Comment by Hyphen-ated** [comment]
Thanks for those bug reports btw!

**Comment by Gol-D-Ace** [comment]
I like your project so I try to contribute to it (well not actual code ;) )

Unfortunately I don't know directly a way to do this.

**Comment by Gol-D-Ace** [comment]
```html
<iframe title="YouTube video player" width="650" height="390" src="http://www.youtube.com/embed/P211w1HuEK4?version=3&vq=hd1080" frameborder="0" allowfullscreen></iframe>
```

 ?version=3&vq=hd1080 should do the trick behind the embed url.
Will also work for videos that don't have 1080p.

**Comment by Hyphen-ated** [comment]
When I try that it doesn't work. Does it work for you? Is this a browser issue maybe

**Comment by Gol-D-Ace** [comment]
This only seems to work with the youtube flash player. The html5 player doesn't like it.

**Comment by Gol-D-Ace** [comment]
Well and Firefox for example will start using html5 by default with Version 36 as well.

So not really a solution...

**Comment by Hyphen-ated** [comment]
The bot does embed the flash player. But in my tests just now, adding those version and vq parameters only succeeds at making it go into high quality if the size of the embed is big enough for the full video

**Comment by Hyphen-ated** [comment]
This guy claims that changing the video quality doesn't affect the audio anymore: http://www.h3xed.com/web-and-internet/youtube-audio-quality-bitrate-240p-360p-480p-720p-1080p

so if true, we don't need to do anything here anyway

**Comment by Gol-D-Ace** [comment]
Apparently this is true. Just tested one of my own videos uploaded in 2011 and I can't notice a difference in audio quality anymore.
