### ISSUE TITLE
Setting webpage server port from yml

### ISSUE THREAD

**Issue by FunkyMiller** [Hyphen-ated/DJBot#25]
Is it possible to add the server port for the webpage as being read from options.yml? I have tomcat running on my machine to host other pages, so localhost:8080 is already in use. Being able to set a different port in the options.yml would make it far easier for this to be avoided.

**Comment by Hyphen-ated** [comment]
Yeah this is a problem. Fixing this also requires changing the javascript code that hardcodes 8080

**Comment by FunkyMiller** [comment]
Yeah. The annoying thing is my work laptop has nothing using 8080, but it still fails. Netstat shows no conflict. Might be 8081 though.

**Comment by Hyphen-ated** [comment]
How does it fail when 8080 is not otherwise in use? are you sure that failure even has to do with the port?

**Comment by FunkyMiller** [comment]
I'm not sure. I have no issue running it at home, but my work laptop crashes with a binding error when it is trying to bind to localhost:8080. I'll try and remember to send through the stacktrace tomorrow when I go back to work.

Date: Tue, 17 Feb 2015 21:40:43 -0800

**Comment by FunkyMiller** [comment]
I got it to work by changing the port in the options.yml, adding the following to the bottom:
server:
  applicationConnectors:
  - type: http
    port: 8090
  adminConnectors:
  - type: http
    port: 8091Obviously I still needed to change the value in the js, not sure if there is any way to dynamically set it, but I'll let you know if I come up with something magic.

Date: Tue, 17 Feb 2015 21:40:43 -0800

**Comment by Hyphen-ated** [comment]
That worked and the js change was trivial; thanks!
