### ISSUE TITLE
Text Encoding issue

### ISSUE THREAD

**Issue by erictfkc** [Hyphen-ated/DJBot#30]
I hope show now playing song title on my broadcast.
Can it made a file which save now playing song info?

Another, when add a Chinese or Japanese word,it will show wrong text,
i want this can be fix~~

Thanks ~ this is a awesome work!

**Comment by Hyphen-ated** [comment]
There's already a ticket for adding a txt file like that, but the problem with asian characters is new to me, I'll check that out

**Comment by Hyphen-ated** [comment]
It was very easy to fix!

**Comment by erictfkc** [comment]
I just see queue.json and unplayedSongs.json.
There are another txt file with now playing track infomation?

**Comment by Hyphen-ated** [comment]
it's not released yet

**Comment by erictfkc** [comment]
Thank you for your responding.
I'm expecting for your new released.

**Comment by Hyphen-ated** [comment]
Version 0.2.0 is released, which has the fix for this
