### ISSUE TITLE
Issues detecting people as mods.

### ISSUE THREAD

**Issue by powerade661** [Hyphen-ated/DJBot#34]
I am thinking this is due to the new CAP authentication for Twitch but it doesn't detect any other mods as moderators when trying to change the volume or skip songs. 

Regards,
Powerade661

**Comment by Escheria** [comment]
To enable JOIN/PART messages you need to request the membership feature, according to http://discuss.dev.twitch.tv/t/join-part-changes-temporary-and-future/2519. 

So a possible fix is to send a raw message with the CAP request (CAP REQ :twitch.tv/membership) before the bot attempts to join the chosen channel.

**Comment by powerade661** [comment]
Yes I understand that, but where would I put the CAP commands? There isn't a server window to just plug in the commands.

**Comment by Escheria** [comment]
Try inserting this 
`this.sendRawLine("CAP REQ :twitch.tv/membership");`
after the following line:
https://github.com/Hyphen-ated/DJBot/blob/master/src/main/java/hyphenated/djbot/DjIrcBot.java#L68

I've not tried this yet cause my copy of DJ Bot is having issues parsing the options >_< So I kind of hope you can test this :/

**Comment by powerade661** [comment]
It's not working, or at least I don't think. I just tested it and mods still can't skip songs. Let me show you what I have for my bot that seems to work fine when detecting mods. 
/raw CAP REQ :twitch.tv/membership
    /raw CAP REQ :twitch.tv/commands

**Comment by Escheria** [comment]
I assume you have tried sending both requests too... Maybe try 'sendRawLineViaQueue' method instead of 'sendRawLine'? (btw: http://www.jibble.org/javadocs/pircbot/org/jibble/pircbot/PircBot.html)

If that doesn't help then we might need Hyphen's help here.

**Comment by powerade661** [comment]
No it's not working and yes I tried both along with sendRawLineViaQueue :(

**Comment by Escheria** [comment]
I'm out of ideas for now :(

**Comment by powerade661** [comment]
The sendRawLineViaQueue actually rendered the code useless.

**Comment by Escheria** [comment]
OK, I got my DJ Bot copy finally working.

The application log says the following:
`INFO  [2015-06-26 22:47:54,711] hyphenated.djbot: Moderator priviliges added for escheria
INFO  [2015-06-26 22:47:54,711] hyphenated.djbot: Moderator priviliges added for eschbot`

So as a matter of fact, I just managed to change the volume and skip songs using my bot account. All I added is `this.sendRawLine("CAP REQ :twitch.tv/membership");`. I'm using version 0.1.9 and not 0.2.0 though.

On my first build after the edit, it would change the volume but not skip the songs, but after a restart I could both change volume and skip songs. Try starting your DJ Bot once again and see the console if the moderator privileges are added o.o

**Comment by powerade661** [comment]
Ok thanks. Lol

**Comment by powerade661** [comment]
What are you thoughts on this Hyphen?

**Comment by Hyphen-ated** [comment]
Looks like you guys figured it out, I'll test that line escheria posted sometime

**Comment by powerade661** [comment]
It doesn't work in 0.2.0 just in 0.1.9

**Comment by Hyphen-ated** [comment]
works fine in 0.2.0 once the other 0.2.0 bug is fixed
