### ISSUE TITLE
DJ Bot version 0.2.0 does not finish starting up.

### ISSUE THREAD

**Issue by Escheria** [Hyphen-ated/DJBot#35]
Trying to start up DJ Bot version 0.2.0 leaves me with a blank console screen. I used a version downloaded directly from the website without any modifications and just edited the options.yaml. However, version 0.1.9 starts up properly, so it can't be a problem with the configuration.

Here is the log from my terminal:
```
escheria@~/Downloads/djbot-0.2-2.0:java -jar djbot.jar server options.yaml 
01:44:19,521 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
01:44:19,521 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
01:44:19,521 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
01:44:19,522 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Setting up default configuration.
01:44:20,491 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@5ba607b4 - Propagating INFO level on Logger[ROOT] onto the JUL framework
01:44:20,498 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
01:44:20,499 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern ./logs/djbot-%d.txt for the active file
01:44:20,501 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern './logs/djbot-%d.txt'.
01:44:20,501 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
01:44:20,503 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Sat Jun 27 01:44:20 CEST 2015
01:44:20,504 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - File property must be set before any triggeringPolicy or rollingPolicy properties
01:44:20,504 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - Visit http://logback.qos.ch/codes.html#rfa_file_after for more information
01:44:20,504 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - Active log file name: ./logs/djbot.txt
01:44:20,504 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - File property is set to [./logs/djbot.txt]
01:44:20,506 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Attaching appender named [file-appender] to AsyncAppender.
01:44:20,507 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Setting discardingThreshold to 51
01:44:20,507 |-INFO in ch.qos.logback.classic.AsyncAppender[async-console-appender] - Attaching appender named [console-appender] to AsyncAppender.
01:44:20,507 |-INFO in ch.qos.logback.classic.AsyncAppender[async-console-appender] - Setting discardingThreshold to 51

INFO  [2015-06-26 23:44:20,528] org.eclipse.jetty.util.log: Logging initialized @1099ms
INFO  [2015-06-26 23:44:20,606] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: assets for path /djbot/ui/*
```

So the only odd thing I see here is the logger, but it apparently gets fixed after the error and version 0.1.9 has same log output yet starts up just fine. So whatever prevents DJ Bot from starting up has to happen after the server window was created.

**Comment by powerade661** [comment]
Yeah I fixed this issue by noticing that I had another java.exe open in task manager. Just a simple restart will fix this for you.

**Comment by Escheria** [comment]
I almost always have a window of Chatty open when my computer is on, which is another Java application, and version 0.1.9 does not conflict with Chatty. I did a full restart as you suggested, didn't help :( 
I'll install Eclipse and try running DJ Bot there to see where exactly does it stop loading.

**Comment by powerade661** [comment]
Try opening it without Chatty. The 0.2.0 version is very iffy.

**Comment by Escheria** [comment]
I did, right after the restart. I'm back from my short walk to the post office, so I'll try to start this up in Eclipse.

**Comment by Escheria** [comment]
Mmkay, my Eclipse catches a Nullpointer Exception with following stack trace:
```
[hyphenated.djbot.DjService.updateNowPlayingFile(DjService.java:594),
hyphenated.djbot.DjService.nextSong(DjService.java:1023),
hyphenated.djbot.DjResource.<init>(DjResource.java:34),
hyphenated.djbot.DjApplication.run(DjApplication.java:48),
hyphenated.djbot.DjApplication.run(DjApplication.java:1),
io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42),
io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76),
io.dropwizard.cli.Cli.run(Cli.java:70),
io.dropwizard.Application.run(Application.java:73),
hyphenated.djbot.DjApplication.main(DjApplication.java:21)]
```
Well, time to dig into this :O Wonder what went wrong with updating the now playing queue.

**Comment by Hyphen-ated** [comment]
That stacktrace is because your config has no "nowPlayingPattern" (or a null one) and I forgot to make it check for that (oops). that's a new thing in the config so trying to use your old config file will cause it. you should take the new config file from the release and edit it to be how you want

**Comment by Escheria** [comment]
Thanks for the pointer Hyphen, indeed I ended up using the old configuration file. However, after I replaced it with the new one and edited in the information, the error is still there with the same stacktrace.

**Comment by Hyphen-ated** [comment]
Can you redact the service keys at the top and pastebin your config file?

**Comment by Escheria** [comment]
Here you go: http://pastebin.com/AbJj4DTq

**Comment by Hyphen-ated** [comment]
oh it was actually happening because you didn't have a currently playing song, my bad. fixed that.

**Comment by Escheria** [comment]
DJ Bot starting up normally now, thanks! :D
