### ISSUE TITLE
Possibility to open youtube links in VLC instead of the webbrowser?

### ISSUE THREAD

**Issue by FusenSho** [Hyphen-ated/DJBot#36]
Hello,
I am looking for a songrequest bot, like yours, that does not open the youtube videos in the browser, since i have some "complicated" audio device setups ;) So, thats why I am asking, if it would be possible to play the video for example in VLC Media Player.

**Comment by Hyphen-ated** [comment]
Can VLC be used to play youtube videos directly, given the URL of the video?

**Comment by FusenSho** [comment]
Yes, vlc is able to play youtube videos directly without any plugins :)
There also was once a Teamspeak 3 Music Bot, that was able to play Youtube Videos in VLC by requesting the videos in the Chat.

**Comment by Hyphen-ated** [comment]
Hmm, so the djbot process would have to control vlc directly I suppose, rather than going through a web layer. Seems like it would be a lot of work. And I'm not sure how I could detect that a song has finished playing in order to trigger the next one.

**Comment by FusenSho** [comment]
Thx for the reply. There is no need to detect a song that has finished, since every added, including every new added song is going to be put into the queue in vlc, when you set the player to 1 instance and list songs into the playlist :) The only thing that is needed, is that the bot executes the command "vlc http://youtube.video" in the home directory of the vlc client and the videos will get added into the playlist :) just try it out by yourself. Open the cmd, go to the home directory of vlc and just type in "vlc https://www.youtube.com/watch?v=SKI1P2gEK54" as an example.

**Comment by Hyphen-ated** [comment]
It will take more than that to make it work with the features djbot has. the bot reports in the chat when a new song comes on and what the title is, it allows mods to skip songs or change the volume, it restricts how many songs a single viewer can have in the queue at a time, and it bumps songs to a backup queue if the requester leaves the chat. Those all seem difficult or not possible with your vlc idea.
if you don't care about any of those features and just want the vlc thing, then you're probably better off making a more minimal bot. maybe the easiest way is to fork this one and tear a bunch of stuff out.

**Comment by FusenSho** [comment]
Hmmm okay, too bad, but i really apreciate your time answering my question :) Ty and a good time with your project ;)
