### ISSUE TITLE
Twitch IRC server migration

### ISSUE THREAD

**Issue by Escheria** [Hyphen-ated/DJBot#41]
Hello everyone!

Twitch has been doing a migration of the chat servers to AWS EC2 and for select partnered streamers, whose chats have already been moved, DJ Bot will not be able to connect to chat servers.

The only thing that should be changed is the hostname:
- irc.chat.twitch.tv supports 80, 6667 (no SSL) and 443, 6697 (SSL)
- irc-ws.chat.twitch.tv supports 80 (no SSL) and 443 (SSL) [Websockets]

I'm not one of the affected users right now, but just pointing out this fact and that it should be addressed because eventually all chat servers will be relocated and should the hostname stay same, DJBot will not work any more.

Source:
https://discuss.dev.twitch.tv/t/psa-chat-servers-are-going-to-migrate-to-aws-ec2-servers/4877

**Comment by Hyphen-ated** [comment]
I made it check http://tmi.twitch.tv/servers?channel=blah at startup to figure out what server to connect to. seems to be working.
My channel's been migrated!
